from django.urls import path 
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('classes/', views.classes, name='classes'),
    path('testimonials/', views.testimonials, name='testimonials'),
    path('faqs/', views.faqs, name='faqs'),
    path('contact/', views.contact, name='contact'),
    path('404/', views.error_404, name='error_404'),
    path('programs/', views.programs, name='programs'),
    path('feedback/', views.feedback, name='feedback'),
    path('customer_registration/', views.customer_registration.as_view(), name='customer_registration'),
    path ('login/', views.Login, name='loginview'),
    path('logout/', views.logout_view, name='logout'),
    path('addtocart/', views.addtocart, name='add_to_cart'),
    path('showcart/', views.showcart, name='showcart'),
    path('remove_cart', views.remove_cart, name='remove_cart'),
    path('pluscart/', views.plus_cart, name='plus_cart'),
    path('minuscart/', views.minus_cart, name='minus_cart'),
    path('weightloss/', views.weight_loss, name='weightloss'),
    path('musclebuilding/', views.muscle_gain_plan, name='musclebuilding'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('protein/', views.Protein, name='protein'),
    path('shirt/', views.shirt, name='shirt'),
    path('shoes/', views.shoes, name='shoes'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-success/', views.order_success, name='order_success'),
    path('orders/', views.orders, name='orders'),
]