# Generated by Django 5.2.11 on 2026-02-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('protein', 'Protein'), ('shirt', 'Shirt'), ('shoes', 'Shoes')], max_length=100),
        ),
    ]
