# Generated by Django 5.2.11 on 2026-02-24 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Trainer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='trainer',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ratting',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
