# Generated by Django 5.2.11 on 2026-02-25 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0004_remove_feedback_trainer_remove_customer_trainer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubcriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strip_id', models.CharField(max_length=100)),
                ('subcription_plan', models.CharField(choices=[('basic', 'basic'), ('premium', 'premium'), ('pro', 'pro')], max_length=100)),
                ('status', models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], max_length=100)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
