# Generated by Django 5.2.11 on 2026-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0005_plan_subcriptionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='disscount_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
