# Generated by Django 5.2.11 on 2026-02-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0006_plan_disscount_price_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriptionmodel',
            name='subcription_plan',
            field=models.CharField(choices=[('basic', 'basic'), ('silver', 'silver'), ('premium', 'premium'), ('pro', 'pro'), ('free', 'free')], max_length=100),
        ),
    ]
